POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
  "email": "22hmv3@queensu.ca",
  "password": "Password"
}

###

POST http://127.0.0.1:8000/api/signup/
Content-Type: application/json

{
  "first_name": "Josh",
  "last_name": "Ossip",
  "email": "josh@queensu.ca",
  "password": "Password",
  "type": "General Member",
  "team": "Pod"
}


###

GET http://127.0.0.1:8000/api/test_token
Content-Type: application/json

{}
