# Generated by Django 5.0.3 on 2024-04-12 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_user_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=50)),
                ("bio", models.CharField(max_length=255)),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, related_name="teams", to="users.user"
                    ),
                ),
            ],
        ),
    ]
