# Generated by Django 5.0.3 on 2024-04-12 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_alter_team_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="title",
            field=models.CharField(max_length=20000),
        ),
    ]
