# Generated by Django 5.0.3 on 2024-04-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("memos", "0001_initial"),
        ("teams", "0003_alter_team_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="memos",
            field=models.ManyToManyField(
                blank=True, related_name="teams", to="memos.memo"
            ),
        ),
    ]
